apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      containers:
        - name: selenium-node-chrome
          image: {{ .Values.image.chrome }}
          env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub-service.default.svc.cluster.local
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"